### ISSUE TITLE
Make it possible to show only the day name, instead of the dayname + date

### ISSUE THREAD

**Issue by rolfberkenbosch** [pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer#1]
Hi,

Can you make it possible to show only the day name, instead of the dayname + date when possible.
Maybe with a specific option like, 
showonlydays: true

Thanks!

**Comment by pippyn** [comment]
I've added 2 new options to the sensor in version 1.1.0 ;
First "dateonly" to remove the dayname, tomorrow or today prefix
Second "dateformat" to let users choose what format they want for the sensor.
Look at the readme for more information.
Please report any issues!
